dist: trusty
sudo: false
language: php

env:
  global:
  - COMPOSER_ARGS="--no-interaction"
  - MAGENTO2_RELEASES_FILE=${TRAVIS_BUILD_DIR}/.bin/shop-releases.txt
  - SHOP_SYSTEM_UPDATE_COMMIT = "[skip ci] Update latest shop releases"
  - BATCH_RELEASE="batch"
  - MINOR_RELEASE="minor"
  - MAJOR_RELEASE="major"

matrix:
  allow_failures:
    - stage: acceptance-test
  include:
  - php: 7.0
    if: env(PHRASEAPP_PULL) != '1' AND type = cron

  - stage: get-magento2-versions
    if: type != cron
    php: 7.1
    install: skip
    before_script: skip
    script: bash .bin/get-magento2-versions.sh
    after_script: skip
    after_failure: skip

  - &acceptance-test
    stage: acceptance-test
#    run this stage on pull request if head branch name contains one of these words (batch, major, minor)
#   or when there is a new shop system version
    if: (type = pull_request AND (head_branch =~ env(BATCH_RELEASE) OR head_branch =~ env(MINOR_RELEASE) OR head_branch =~ env(MAJOR_RELEASE))) OR commit_message =~ env(SHOP_SYSTEM_UPDATE_COMMIT)
  
    #    if: (type = pull_request AND \
#    ((head_branch =~ env(BATCH_RELEASE)) OR (head_branch =~ env(MINOR_RELEASE)) OR (head_branch =~ env(MAJOR_RELEASE)))) OR \
#      (commit_message =~ env(SHOP_SYSTEM_UPDATE_COMMIT))
#   run tests with shop extension current branch version (master or RC-X.X.X-type)
    php: 7.1
    env:
    - GATEWAY=API-TEST
    - MAGENTO2_RELEASE_VERSION=1
    install:
      - export MAGENTO2_VERSION=$(awk "NR==$MAGENTO2_RELEASE_VERSION {print; exit}" ${MAGENTO2_RELEASES_FILE})
      - bash .bin/remove-composer-lock-file.sh
      - travis_retry composer require --dev $COMPOSER_ARGS phpunit/phpunit ^5.7
      - travis_retry composer require --dev $COMPOSER_ARGS codeception/codeception:^2.5
      - travis_retry composer install $COMPOSER_ARGS
    script: bash .bin/run-ui-tests.sh
    after_script: skip
    after_success:
      - bash .bin/upload-logs-and-notify.sh
    after_failure:
      - bash .bin/upload-logs-and-notify.sh fail
 
#  - <<: *acceptance-test
##    run this stage on pull request if head branch name contains one of these words (batch, major, minor)
##    run tests with shop extension current branch version (master or RC-X.X.X-type)
#    if: type = pull_request AND \
#      ((head_branch =~ env(BATCH_RELEASE)) OR (head_branch =~ env(MINOR_RELEASE)) OR (head_branch =~ env(MAJOR_RELEASE)))
#    env:
#    - GATEWAY=API-TEST
#    - MAGENTO2_RELEASE_VERSION=2
##   run this stage on pull request if head branch name contains one of these words (batch, major, minor)
##   run tests with shop extension current branch version (master or RC-X.X.X-type)
#
#  - <<: *acceptance-test
#    #    run this stage on pull request if head branch name contains one of these words (batch, major, minor)
#    #    run tests with shop extension current branch version (master or RC-X.X.X-type)
#    if: type = pull_request AND \
#      ((head_branch =~ env(BATCH_RELEASE) ) OR (head_branch =~ env(MINOR_RELEASE)) OR (head_branch =~ env(MAJOR_RELEASE)))
#    env:
#    - GATEWAY=API-TEST
#    - MAGENTO2_RELEASE_VERSION=3
##    run this stage when shop system updated with latest shop extension release version
#  - <<: *acceptance-test
#    # when commit message contains string "Update latest shop releases"
#    if: commit_message =~ env(SHOP_SYSTEM_UPDATE_COMMIT)
#    env:
#    - GATEWAY=API-TEST
#    - MAGENTO2_RELEASE_VERSION=1
#    - LATEST_EXTENSION_RELEASE=1


  - stage: phraseapp-pull
    if: env(PHRASEAPP_PULL) = '1'
    language: ruby
    ruby: 2.5.3
    before_install: skip
    install:
    - travis_retry gem install bundler -v 2.0.1
    - travis_retry bundle install
    script:
    - .bin/rake phraseapp:ci_update
    after_script: skip

  - stage: phraseapp-check-if-in-sync
    if: type = cron AND type != pull_request
    language: ruby
    ruby: 2.5.3
    before_install: skip
    install:
    - travis_retry gem install bundler -v 2.0.1
    - travis_retry bundle install
    script:
    - .bin/rake phraseapp:ci_check_if_in_sync
    after_script: skip

  - stage: deploy
    if: tag IS present AND type = push
    language: php
    php: 7.0
    before_install: skip
    install:
      - travis_retry composer install $COMPOSER_ARGS
      - rvm install 2.5.3
      - travis_retry gem install bundler -v 2.0.1
    after_install: skip
    before_script: skip
    script: skip
    after_script: skip
    before_deploy:
    - export REPO_NAME=`echo $TRAVIS_REPO_SLUG | awk -F'/' '{print $2}'`
    - export RELEASE_NOTES=$(composer make-release-notes)
    - bash .bin/generate-wiki-notes.sh
    - bash .bin/generate-readme-badge.sh
    deploy:
      provider: releases
      github_token: ${GITHUB_TOKEN}
      api_key: ${GITHUB_TOKEN}
      name: "${REPO_NAME} ${TRAVIS_TAG}"
      body: "${RELEASE_NOTES}"
      skip_cleanup: true
      on:
        repo: ${TRAVIS_REPO_SLUG}
        tags: true
    after_deploy:
    - export TMPDIR=/tmp/wirecard
    - git clone -b master --depth 1 https://$WIRECARD_CEE_GITHUB_TOKEN@github.com/$DEPLOYMENT_PROJECT $TMPDIR
    - cd $TMPDIR && travis_retry bundle install
    - bin/rake trigger_build

install:
  - travis_retry composer require --dev $COMPOSER_ARGS satooshi/php-coveralls:^1.0
  - travis_retry composer install $COMPOSER_ARGS
  - composer show

script:
  - composer test-coverage
  - composer cs-check

after_script:
  - composer upload-coverage
  - bash .bin/generate-tag.sh

notifications:
  email: false
  slack:
    rooms:
      secure: YI7sUrfMyKyJD60kElGkO7yBDkGEh+069yS8bFAIDUST7s48J+dDP/r2G9dN9oQwhs9hvNjpNytpZDPys838T+Z0mNtFZ9Wu022hV3MpbKUuMl7L9P0MQQmxjg4bKyKK3Hl9tPrZ3UsKRlwIUmRGGYQ7cjs4zumorqs19YsB3X+WnnxAmmYB3kHQYfNKgVnmcG2QHJyx5KaLZ0EsWynSHXkYb8bVCtdlbQFNnpChvGHPprZrHAszLCYnlU7AEZGdbuk17oIfXO9Wjuu1GV8iJ2VgKkTCzW4FBC5eHJyZezojPFUm1I5tvdihRZuyBekVGOF23J6pvHLqPx77clT+/Vn6T+UMDuh1INZ0LKt4UOU42oEDKGblWZx2VYWcHwfEK+ckJWZkT9EBfg/CMenJly2tbtBj6++XNvxgGEDn6XqKIEatcb7X/aiy4f8BPXa3/pzgZAlvzZbGGqHFNZPAlgcXBBXgbaC7VvMhvi6Z5AG5ylKzPS5GCD95ozPC+cGv0234TBJus5oZck4qNiT53IUQ7Ta+OGVB0Mea105VAoQI0I7YcgaqW6c4h2YTmnuuQsIzAwPOrJ5TAinj8Z8mZ9C11tEcNF3Pgy1tOoG/YLurhOJm7v1ebotRb/DIeSHU8RfNatnDSSky4YS6Y8k2pQthdC9m7m2f2mJYuGdLjlM=
    template:
      - "%{repository}#%{build_number} (%{branch} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
    on_success: change
    on_failure: change
